# Generated by Django 5.1.1 on 2025-05-18 06:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_ingredient_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userweight',
            options={'get_latest_by': 'date', 'ordering': ['-date'], 'verbose_name': 'Weight Record', 'verbose_name_plural': 'Weight Records'},
        ),
        migrations.AlterField(
            model_name='userweight',
            name='bmi',
            field=models.FloatField(help_text='Calculated Body Mass Index (BMI).', validators=[django.core.validators.MinValueValidator(10, message='Invalid BMI value'), django.core.validators.MaxValueValidator(60, message='Invalid BMI value')]),
        ),
        migrations.AlterField(
            model_name='userweight',
            name='notes',
            field=models.TextField(blank=True, help_text='Optional notes on user progress.', null=True),
        ),
        migrations.AlterField(
            model_name='userweight',
            name='weight',
            field=models.FloatField(help_text="User's weight in kilograms.", validators=[django.core.validators.MinValueValidator(20, message='Weight must be at least 20kg'), django.core.validators.MaxValueValidator(300, message='Weight must be less than 300kg')]),
        ),
        migrations.AddConstraint(
            model_name='userweight',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='unique_weight_entry_per_day'),
        ),
    ]
