# Generated by Django 5.1.1 on 2025-05-18 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_userweight_options_alter_userweight_bmi_and_more'),
    ]

    operations = [
    ]
